---
title: "STT 811 Project"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
grocery <- read.csv("grocery_inventory_clean.csv")
```

```{r, results='hide'}
library(tidyverse)
library(ggplot2)
library(ggiraph)
library(caret)
library(xgboost)
library(randomForest)
library(nnet)
library(dplyr)
```

```{r}
grocery$FIFO_FEFO <- as.factor(grocery$FIFO_FEFO)
grocery$Inventory_Status <- as.factor(grocery$Inventory_Status)
grocery$ABC_Class <- as.factor(grocery$ABC_Class)
stock_variables <- c("Quantity_On_Hand", "Quantity_Reserved", "Quantity_Committed", "Damaged_Qty", "Returns_Qty", "Inventory_Status", "FIFO_FEFO",
"Stock_Age_Days")
planning_variables <- c("Avg_Daily_Sales", "Forecast_Next_30d", "Days_of_Inventory", "Reorder_Point", "Safety_Stock", "Lead_Time_Days", "SKU_Churn_Rate", "Order_Frequency_per_month")
financial_variables <- c("Unit_Cost_USD", "Last_Purchase_Price_USD", "Total_Inventory_Value_USD", "Supplier_OnTime_Pct", "Demand_Forecast_Accuracy_Pct", "Audit_Variance_Pct", "Count_Variance")
grocery_stock_status <- grocery[c(stock_variables, 'ABC_Class')]
grocery_planning_velocity <- grocery[c(planning_variables, 'ABC_Class')]
grocery_financial_quality <- grocery[c(financial_variables, 'ABC_Class')]
```

```{r}
split_pct <- 0.8
n <- length(grocery$ABC_Class)*split_pct
row_samp <- sample(1:length(grocery$ABC_Class), n, replace = FALSE)
train <- grocery[row_samp,]
test <- grocery[-row_samp,]
train_stock_status <- grocery_stock_status[row_samp,]
test_stock_status <- grocery_stock_status[-row_samp,]
train_planning_velocity <- grocery_planning_velocity[row_samp,]
test_planning_velocity <- grocery_planning_velocity[-row_samp,]
train_financial_quality <- grocery_financial_quality[row_samp,]
test_financial_quality <- grocery_financial_quality[-row_samp,]
```

```{r}
grocery_stock_rf <- randomForest(ABC_Class ~ . - ABC_Class, 
                      data = train_stock_status, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_stock <- predict(grocery_stock_rf, test_stock_status)
confusionMatrix(rf_predict_stock, as.factor(test_stock_status$ABC_Class))
barplot(grocery_stock_rf$importance[,3])
```
```{r}
grocery_planning_rf <- randomForest(ABC_Class ~ . - ABC_Class, 
                      data = train_planning_velocity, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_planning <- predict(grocery_planning_rf,  test_planning_velocity)
confusionMatrix(rf_predict_planning, as.factor(test_planning_velocity$ABC_Class))
barplot(grocery_planning_rf$importance[,3])
```

```{r}
grocery_financial_rf <- randomForest(ABC_Class ~ . - ABC_Class,
                      data = train_financial_quality, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_financial <- predict(grocery_financial_rf, test_financial_quality)
confusionMatrix(rf_predict_financial, as.factor(test_financial_quality$ABC_Class))
barplot(grocery_financial_rf$importance[,3])
```
```{r}
grocery_financial_rf <- randomForest(ABC_Class ~ . - ABC_Class - Total_Inventory_Value_USD,
                      data = train_financial_quality, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_financial <- predict(grocery_financial_rf, test_financial_quality)
confusionMatrix(rf_predict_financial, as.factor(test_financial_quality$ABC_Class))
barplot(grocery_financial_rf$importance[,3])
```
```{r}
grocery_financial_rf <- randomForest(ABC_Class ~ Total_Inventory_Value_USD,
                      data = train_financial_quality, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_financial <- predict(grocery_financial_rf, test_financial_quality)
confusionMatrix(rf_predict_financial, as.factor(test_financial_quality$ABC_Class))
#barplot(grocery_financial_rf$importance[,3])
```
```{r}
grocery_tester_rf <- randomForest(ABC_Class ~ Unit_Cost_USD + Quantity_On_Hand + Avg_Daily_Sales,
                      data = train, mtry = 2, 
                      importance = TRUE, ntree = 1000, maxnodes = 4)
rf_predict_tester <- predict(grocery_tester_rf, test)
confusionMatrix(rf_predict_tester, as.factor(test$ABC_Class))
barplot(grocery_tester_rf$importance[,3])
```



```{r}
ggplot(grocery, aes(x = ABC_Class, y = Total_Inventory_Value_USD, fill = ABC_Class)) +
  geom_boxplot() +
  labs(title = "ABC Class vs Total Inventory Value USD",
       x = "ABC Class",
       y = "Total Inventory Value USD") +
  theme_minimal()
```

```{r}
model_logit <- multinom(
  ABC_Class ~ Total_Inventory_Value_USD,
  data = train)

pred_logit <- predict(model_logit, test)
mean(pred_logit == test$ABC_Class)
```

```{r}
ggplot(grocery, aes(x = Total_Inventory_Value_USD, y = ABC_Class, color = ABC_Class)) +
  geom_jitter(alpha = 0.5) +
    labs(title = "Total Inventory Value USD vs ABC Class",
       y = "ABC Class",
       x = "Total Inventory Value USD") +
  theme_minimal()
```
```{r}
grocery %>%
  group_by(ABC_Class) %>%
  summarise(
    'Lowest Value' = min(Total_Inventory_Value_USD, na.rm = TRUE),
    'Highest Value' = max(Total_Inventory_Value_USD, na.rm = TRUE))
```


```{r}
abc_class_solver <- grocery[c('Quantity_On_Hand', 'Quantity_Reserved', 'Quantity_Committed', 'Unit_Cost_USD', 'Last_Purchase_Price_USD', 'Avg_Daily_Sales', 'ABC_Class', 'Total_Inventory_Value_USD')]
abc_class_solver['verification1'] <- abc_class_solver['Quantity_On_Hand'] * abc_class_solver['Unit_Cost_USD']
abc_class_solver['verification2'] <- abc_class_solver['Quantity_On_Hand'] * abc_class_solver['Last_Purchase_Price_USD']
abc_class_solver['verification3'] <- abc_class_solver['Avg_Daily_Sales'] * abc_class_solver['Unit_Cost_USD']
head(abc_class_solver)
```

```{r}
abc_class_solver$percent_error <- round(abs(abc_class_solver$verification1 - abc_class_solver$Total_Inventory_Value_USD) / abc_class_solver$Total_Inventory_Value_USD * 100, 5)
head(abc_class_solver)
```

```{r}
ggplot(abc_class_solver, aes(x = Total_Inventory_Value_USD, y = verification1, color = ABC_Class)) +
  geom_jitter(alpha = 0.5) +
    labs(title = "Total Inventory Value USD vs ABC Class Predicted Value",
       y = "Unit Cost * Quantity on Hand",
       x = "Total Inventory Value USD") +
  theme_minimal()
```